steps:
# ... (langkah-langkah build, push, deploy Anda tetap sama) ...
- name: 'gcr.io/google-appengine/exec-wrapper'
  args:
  - '/bin/bash'
  - '-c'
  - |
    gcloud run deploy $_SERVICE_NAME \
      --image asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-app-repo/$_SERVICE_NAME:$SHORT_SHA \
      --region asia-southeast1 \
      --platform managed \
      --allow-unauthenticated

images:
- 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-app-repo/$_SERVICE_NAME:$SHORT_SHA'

# TAMBAHKAN BLOK INI
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'